### ISSUE TITLE
UTF-16 XML documents cause exception

### ISSUE THREAD

**Issue by execextreme** [RealGeeks/evernetpy#4]
When trying to get photos, a handful (roughly 1500) listings will return XML documents encoded in UTF-16 which raises a ParseError in parser.py

I worked around this with the following:

        from xml.etree.ElementTree import iterparse, ParseError
        from StringIO import StringIO

        def parse(data):
            # workaround
            mystr = ''
            for line in data:
                mystr += line

            try:
                for event, elem in iterparse(StringIO(mystr)):
                    if elem.tag in TAGS_I_CARE_ABOUT:
                        yield elem
                        elem.clear()
            except ParseError:
                mystr = mystr.encode('utf-16-be')

                for event, elem in iterparse(StringIO(mystr)):
                    if elem.tag in TAGS_I_CARE_ABOUT:
                        yield elem
                        elem.clear()

**Comment by kevin1024** [comment]
Thanks!  Just got this message from the mailing list:

Early this morning we received reports that a couple of IDX consumers were encountering errors when parsing results from our EverNet Image Service.  The errors indicated that the document was not encoded correctly or that there was UTF-8 content in a UTF-16 document.



This has been corrected and the XML returned now properly honors the encoding of the declaration.



We apologize for the inconvenience.



NWMLS IDX Support
